### ISSUE TITLE
August meetup [tracking issue]

### ISSUE THREAD

**Issue by broccolini** [design-systems-coalition-NYC/meetup#29]
Date: **August 17th, 6.30pm**
Host: **DoSomething**
Topic: **Empowering product growth with design systems**

## Tracking
- [x] **Announce meetup**
  - [x] Meetup event created & posted (4 weeks prior)
  - [x] Tweet "save the date"
  - [x] "Save the date" link added to website
- [x] **Confirm speakers**
  - [x] Luke Patton
  - [x] Una Kravets
  - [x] Jina Anne
- [x] **Announce speakers & RSVP's** (ideally 3 weeks prior)
  - [x] Meetup event updated with speakers
  - [x] Announce event with speakers on website, archive previous event
  - [x] RSVP's open on meetup (3 weeks prior)
  - [x] Tweet speakers & rsvp's
- [x] **Speaker prep**
  - [x] Send calendar invite for event with time and location
  - [x] 1:1 with speaker to prep for talk
    - [x] Luke Patton
    - [x] ~~Una Kravets~~ unavailable for call, email
    - [x] ~~Jina Anne~~ unavailable for call, email
  - [x] Draft panel questions & share with speakers for feedback (1 weeks prior)
  - [x] ~~Book call with all speakers~~ async email
  - [ ] Run through talks and panel questions with speakers (1 week prior)
- [x] **Reminders**
  - [x] Increase RSVP limit (1 week out)
  - [x] Tweet reminder about upcoming event (1 week prior)
  - [x] Send reminder to update RSVP weekend prior to event
  - [x] Tweet update RSVP reminder
  - [x] Increase RSVP limit 1 day prior
- [x] **Host prep**
  - [x] Confirm whether event will be recorded, if so:
    - [x] Update meetup to say "this event will be recorded"
    - [x] Check with speakers re recording
  - [x] Send running sheet (1 week prior)
  - [x] Confirm registration process (security & volunteers for registration)
  - [x] Confirm seating setup
  - [x] Check building accessibility
  - [x] Check what time organizers & speakers can arrive for setup - 6pm
  - [x] Send or print out rsvp spreadsheet (5pm day of)
- [ ] **Post event**
  - [x] Tweet thank you to host and speakers
  - [x] Message speakers to thank them again for speaking and check in re slides
  - [ ] Update website with speakers slides, add "save the date" if next event is confirmed
  - [x] Cover photo for video chosen
  - [ ] Photography short-list created
  - [ ] Photographs edited and shared for uploading
  - [ ] Event page created, photos, slides, & video uploaded
  - [ ] Homepage updated to promote event photos & videos
  - [ ] Tweet photos, videos, & slides
