### ISSUE TITLE
October meetup [tracking issues]

### ISSUE THREAD

**Issue by broccolini** [design-systems-coalition-NYC/meetup#36]
**Date: October 4th, 6.30pm
Host: The New York Times
Topic: Design Principles**

## Tracking
- [x] **Announce meetup**
  - [x] Meetup event created & posted (min 6 weeks prior)
  - [x] Tweet "save the date"
  - [x] "Save the date" link added to website
- [x] **Confirm speakers**
  - [x] Orr Shtuhl (Wirecutter)
  - [x] Caitlin Osbahr (Buzzfeed)
  - [x] Michael Jovel (FDA)
- [x] **Announce speakers & RSVP's**
  - [x] RSVP's open on meetup (ideally 4-6 weeks prior)
  - [x] Tweet RSVP's
  - [x] Meetup event updated with speakers
  - [x] Announce event with speakers on website, archive previous event
  - [x] Tweet speakers
- [x] **Speaker prep**
  - [x] Send calendar invite for event with time and location
  - [x] 1:1 with speaker to prep for talk
    - [x] Orr Shtuhl
    - [x] Caitlin Osbahr
    - [x] Michael Jovel
  - [ ] Draft panel questions & share with speakers for feedback (2 weeks prior)
  - [ ] Book call with all speakers
  - [x] Run through talks and panel questions with speakers (1 week prior)
- [ ] **Reminders**
  - [x] Increase RSVP limit (1 week out)
  - [x] Tweet reminder about upcoming event (1 week prior)
  - [x] Send reminder to update RSVP weekend prior to event
  - [x] Tweet update RSVP reminder
  - [x] Increase RSVP limit 1 day prior
- [x] **Host prep**
  - [x] Confirm AV setup
  - [x] Send slide loop template
  - [x] Confirm whether event will be recorded, if so:
    - [ ] Update meetup to say "this event will be recorded"
    - [x] Check with speakers re recording
  - [x] Send running sheet (1 week prior)
  - [x] Confirm registration process (security & volunteers for registration)
  - [x] Confirm seating setup
  - [x] Check what time organizers & speakers can arrive for setup
  - [x] Send or print out rsvp spreadsheet (5pm day of)
- [x] **Post event**
  - [x] Tweet thank you to host and speakers
  - [x] Message speakers to thank them again for speaking and check in re slides
  - [ ] Update website with speakers slides, add "save the date" if next event is confirmed
  - [ ] Cover photo for video chosen
  - [ ] Photography short-list created
  - [ ] Photographs edited and shared for uploading
  - [ ] Event page created, photos, slides, & video uploaded
  - [ ] Homepage updated to promote event photos & videos
  - [ ] Tweet photos, videos, & slides
