### ISSUE TITLE
March meetup [tracking issue]

### ISSUE THREAD

**Issue by broccolini** [design-systems-coalition-NYC/meetup#41]
**Date: March 8th, 6.30pm**
**Venue: tbc**
**Topic: tbc**

---

## Tracking
- [x] **Announce meetup**
  - [x] Meetup event created & posted (4 weeks prior)
  - [x] Tweet "save the date"
  - [x] "Save the date" link added to website
- [x] **Confirm speakers**
  - [x] Speaker 1
  - [x] Speaker 2
  - [x] Speaker 3
- [ ] **Announce speakers & RSVP's**
  - [x] RSVP's open on meetup (ideally 4-6 weeks prior)
  - [x] Tweet RSVP's
  - [ ] Meetup event updated with speakers
  - [ ] Announce event with speakers on website, archive previous event
  - [ ] Tweet speakers
- [ ] **Speaker prep**
  - [ ] Send calendar invite for event with time and location
  - [x] 1:1 with speaker to prep for talk
    - [x] Speaker 1
    - [ ] Speaker 2
    - [ ] Speaker 3
  - [ ] Draft panel questions & share with speakers for feedback (2 weeks prior)
  - [ ] Book call with all speakers
  - [ ] Run through talks and panel questions with speakers (1 week prior)
- [ ] **Reminders**
  - [ ] Increae RSVP limit 2 weeks out
  - [ ] Tweet Event reminder w/ link to RSVP
  - [ ] Increase RSVP limit 1 week out
  - [ ] Tweet reminder about upcoming event 1 week prior
  - [ ] Send reminder to update RSVP weekend prior to event
  - [ ] Tweet update RSVP reminder a few days before event
  - [ ] Increase RSVP limit 1 day prior
  - [ ] Tweet event reminder morning of event
- [ ] **Host prep**
  - [x] Confirm AV setup
  - [ ] Send slide loop template
  - [x] Confirm whether event will be recorded, if so:
    - [ ] Update meetup to say "this event will be recorded"
    - [ ] Check with speakers re recording
  - [ ] Send running sheet (1 week prior)
  - [ ] Send slides loop
  - [ ] Confirm registration process (security & volunteers for registration)
  - [x] Confirm seating setup
  - [ ] Check what time organizers & speakers can arrive for setup
  - [ ] Send or print out rsvp spreadsheet (5pm day of)
- [ ] **Post event**
  - [x] Tweet thank you to host and speakers
  - [ ] Message speakers to thank them again for speaking and check in re slides
  - [ ] Update website with speakers slides, add "save the date" if next event is confirmed
  - [ ] Cover photo for video chosen
  - [ ] Photography short-list created
  - [ ] Photographs edited and shared for uploading
  - [ ] Event page created, photos, slides, & video uploaded
  - [ ] Homepage updated to promote event photos & videos
  - [ ] Tweet photos, videos, & slides
