### ISSUE TITLE
May happy hour

### ISSUE THREAD

**Issue by broccolini** [design-systems-coalition-NYC/meetup#44]
Date: 5/23/18
Location: The Winslow

## Tracking
- [x] **Announce meetup**
  - [x] Meetup event created & posted
- [ ] **Reminders**
  - [x] Increae RSVP limit 2 weeks out
  - [x] Tweet Event reminder w/ link to RSVP
  - [x] Increase RSVP limit 1 week out
  - [x] Tweet reminder about upcoming event 1 week prior
  - [x] Send reminder to update RSVP weekend prior to event
  - [x] Tweet update RSVP reminder a few days before event
  - [ ] Increase RSVP limit 1 day prior
  - [x] Tweet event reminder morning of event
- [ ] **Post event**
  - [ ] Tweet thank you to attendees
