### ISSUE TITLE
June meetup tracking issue

### ISSUE THREAD

**Issue by broccolini** [design-systems-coalition-NYC/meetup#50]
Date: June 20th
Host: Betterment
Topic: Design System API's and the developer experience

## Tracking
- [x] **Announce meetup**
  - [x] Meetup event created & posted (4 weeks prior)
  - [x] Tweet "save the date"
  - [x] "Save the date" link added to website
- [x] **Confirm speakers**
  - [x] Speaker 1
  - [x] Speaker 2
  - [x] Speaker 3
- [x] **Announce speakers & RSVP's**
  - [x] RSVP's open on meetup (ideally 4-6 weeks prior)
  - [x] Tweet RSVP's
  - [x] Meetup event updated with speakers
  - [x] Announce event with speakers on website, archive previous event
  - [x] Tweet speakers
- [x] **Speaker prep**
  - [x] Send calendar invite for event with time and location
  - [x] 1:1 with speaker to prep for talk
    - [x] Connor McNabb & Arielle Sullivan
    - [x] Jenn Creighton
    - [x] Stephanie Manwaring
  - [ ] Draft panel questions & share with speakers for feedback (2 weeks prior)
  - [ ] Book call with all speakers
  - [ ] Run through talks and panel questions with speakers (1 week prior)
- [x] **Reminders**
  - [x] Increae RSVP limit 2 weeks out
  - [x] Tweet Event reminder w/ link to RSVP
  - [x] Increase RSVP limit 1 week out
  - [x] Tweet reminder about upcoming event 1 week prior
  - [ ] Send reminder to update RSVP weekend prior to event
  - [ ] Tweet update RSVP reminder a few days before event
  - [x] Increase RSVP limit 1 day prior
  - [x] Tweet event reminder morning of event
- [ ] **Host prep**
  - [x] Confirm AV setup
  - [x] Send slide loop template
  - [x] Confirm whether event will be recorded, if so:
    - [ ] Update meetup to say "this event will be recorded"
    - [ ] Check with speakers re recording
  - [ ] Send running sheet (1 week prior)
  - [x] Send slides loop
  - [x] Confirm registration process (security & volunteers for registration)
  - [ ] Confirm seating setup
  - [ ] Check what time organizers & speakers can arrive for setup
  - [ ] Send or print out rsvp spreadsheet (5pm day of)
- [ ] **Post event**
  - [ ] Tweet thank you to host and speakers
  - [ ] Message speakers to thank them again for speaking and check in re slides
  - [ ] Update website with speakers slides, add "save the date" if next event is confirmed
  - [ ] Cover photo for video chosen
  - [ ] Photography short-list created
  - [ ] Photographs edited and shared for uploading
  - [ ] Event page created, photos, slides, & video uploaded
  - [ ] Homepage updated to promote event photos & videos
  - [ ] Tweet photos, videos, & slides
